export const itemsLembaga = [{
  "nama-lembaga": "Sybilla",
  "jumlah-anggaran": "27711321.53"
}, {
  "nama-lembaga": "Andonis",
  "jumlah-anggaran": "28607548.38"
}, {
  "nama-lembaga": "Domenic",
  "jumlah-anggaran": "69509997.68"
}, {
  "nama-lembaga": "Chevy",
  "jumlah-anggaran": "98056200.89"
}, {
  "nama-lembaga": "Cassandry",
  "jumlah-anggaran": "98027809.69"
}, {
  "nama-lembaga": "Christi",
  "jumlah-anggaran": "78608410.24"
}, {
  "nama-lembaga": "Augusta",
  "jumlah-anggaran": "97144351.43"
}]

export const itemsKegiatan = [{
  "nama-kegiatan": "Sybilla",
  "anggaran": "27711321.53"
}, {
  "nama-kegiatan": "Andonis",
  "anggaran": "28607548.38"
}, {
  "nama-kegiatan": "Domenic",
  "anggaran": "69509997.68"
}]

export const itemsPemohon = [{
  "nama": "Jemmy",
  "dari-lembaga": "Shufflebeat",
  "no-spd": 696802,
  "nip": 1809810,
  "golongan": "Pall",
  "jabatan": "Jud",
  "status-spd": "Ilyse",
  "status-permohonan": "Ola"
}, {
  "nama": "Melina",
  "dari-lembaga": "Buzzdog",
  "no-spd": 914439,
  "nip": 4989747,
  "golongan": "Tracee",
  "jabatan": "Hartley",
  "status-spd": "Babs",
  "status-permohonan": "Mignonne"
}, {
  "nama": "Wilmette",
  "dari-lembaga": "Demivee",
  "no-spd": 930332,
  "nip": 2774139,
  "golongan": "Bennie",
  "jabatan": "Maxi",
  "status-spd": "Lorne",
  "status-permohonan": "Jobi"
}, {
  "nama": "Rayna",
  "dari-lembaga": "Zooxo",
  "no-spd": 702474,
  "nip": 346857,
  "golongan": "Madelle",
  "jabatan": "Hally",
  "status-spd": "Yancy",
  "status-permohonan": "Wenona"
}, {
  "nama": "Ber",
  "dari-lembaga": "Yozio",
  "no-spd": 170614,
  "nip": 7434693,
  "golongan": "Chuck",
  "jabatan": "Rochester",
  "status-spd": "Gabby",
  "status-permohonan": "Keri"
}, {
  "nama": "Alexis",
  "dari-lembaga": "Eimbee",
  "no-spd": 718478,
  "nip": 2730408,
  "golongan": "Dolorita",
  "jabatan": "Caron",
  "status-spd": "Alverta",
  "status-permohonan": "Harley"
}, {
  "nama": "Dannel",
  "dari-lembaga": "Lajo",
  "no-spd": 462502,
  "nip": 3126718,
  "golongan": "Clerkclaude",
  "jabatan": "Vladamir",
  "status-spd": "Freeman",
  "status-permohonan": "Welby"
}]